
server:
  port: 9980

spring:
  datasource:
    td-engine:
      # 单数据源用url，多数据源用jdbc-url
      # 域名得和tdengine域名相同
      jdbc-url: jdbc:TAOS://tdengine:6030/monitor_point_data?charset=UTF-8&locale=en_US.UTF-8&serverTimezone=Asia/Shanghai   # 6030
#      jdbc-url: jdbc:TAOS-RS://175.178.8.159:6041/monitor_point_data?charset=UTF-8  # 6041
      username: root
      password: ontoweb
      driver-class-name: com.taosdata.jdbc.TSDBDriver  # 6030
#      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver  # 6041
    mysql:
      jdbc-url: jdbc:mysql://150.158.55.26:8066/jeecg_coldrolling?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
#      jdbc-url: jdbc:mysql://10.162.33.202:8066/jeecg_coldrolling?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
      username: mycat
      password: bwzw
      driver-class-name: com.mysql.cj.jdbc.Driver


#多数据源配置tdengine无法启动 Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/http/HttpResponse

#spring:
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      datasource:
#        master:
#          url: jdbc:TAOS-RS://10.162.33.202:52783/monitor_point_data?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
#          username: root
#          password: ontoweb
#          driver-class-name: com.taosdata.jdbc.rs.RestfulDriver # 3.2.0开始支持SPI可省略此配置
#          druid:
#            initial-size: 5
#            min-idle: 5
#            max-active: 5
#        slave_1:
#          url: jdbc:mysql://10.162.33.202:3306/jeecg_coldrolling?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
#          username: root
#          password: ontoweb
#          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: ASSIGN_ID
  configuration:
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml
